name: tabnews
description: "Cliente para visualizar e interagir com as notícias/artigos publicados no TabNews."

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/softyesti/tabnews_client

version: 0.3.0+3

environment:
  sdk: ^3.7.2
  flutter: ^3.29.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  dart_mappable: ^4.0.1
  get: ^4.6.6
  ionicons: ^0.2.2
  google_fonts: ^6.1.0
  flutter_markdown: ^0.7.1
  url_launcher: ^6.2.5
  markdown: ^7.2.1
  feather_icons: ^1.2.0
  solar_icons: ^0.0.5
  hive: ^2.2.3
  path_provider: ^2.1.4
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0
  dart_mappable_builder: ^4.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_foreground: "assets/adaptive_icon.png"
  adaptive_icon_background: "assets/adaptive_icon_bg.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#0D1117"
    theme_color: "#0D1117"

flutter_native_splash:
  color: "#0D1117"
  android: true
  ios: true
  web: true
  android_12:
    branding: assets/branding.png
